version: '3'
services:
  streamlit_app:
    build:
      context: .
    container_name: procurement-bot
    ports:
      - "8501:8501"

    deploy:
      resources:
        limits:
          memory: 6G
